// Copyright 2018 The NuxUI Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// +build android

package nux

// @see https://developer.android.com/ndk/reference/group/input
// @see https://cs.android.com/android/platform/superproject/+/master:frameworks/native/include/android/keycodes.h
const (
	KeyCode_Unknown                   KeyCode = 0   // AKEYCODE_UNKNOWN                       = 0
	KeyCode_SoftLeft                  KeyCode = 1   // AKEYCODE_SOFT_LEFT                     = 1
	KeyCode_SoftRight                 KeyCode = 2   // AKEYCODE_SOFT_RIGHT                    = 2
	KeyCode_Home                      KeyCode = 3   // AKEYCODE_HOME                          = 3
	KeyCode_Back                      KeyCode = 4   // AKEYCODE_BACK                          = 4
	KeyCode_Call                      KeyCode = 5   // AKEYCODE_CALL                          = 5
	KeyCode_Endcall                   KeyCode = 6   // AKEYCODE_ENDCALL                       = 6
	KeyCode_0                         KeyCode = 7   // AKEYCODE_0                             = 7
	KeyCode_1                         KeyCode = 8   // AKEYCODE_1                             = 8
	KeyCode_2                         KeyCode = 9   // AKEYCODE_2                             = 9
	KeyCode_3                         KeyCode = 10  // AKEYCODE_3                             = 10
	KeyCode_4                         KeyCode = 11  // AKEYCODE_4                             = 11
	KeyCode_5                         KeyCode = 12  // AKEYCODE_5                             = 12
	KeyCode_6                         KeyCode = 13  // AKEYCODE_6                             = 13
	KeyCode_7                         KeyCode = 14  // AKEYCODE_7                             = 14
	KeyCode_8                         KeyCode = 15  // AKEYCODE_8                             = 15
	KeyCode_9                         KeyCode = 16  // AKEYCODE_9                             = 16
	KeyCode_Star                      KeyCode = 17  // AKEYCODE_STAR                          = 17
	KeyCode_Pound                     KeyCode = 18  // AKEYCODE_POUND                         = 18
	KeyCode_DpadUp                    KeyCode = 19  // AKEYCODE_DPAD_UP                       = 19
	KeyCode_DpadDown                  KeyCode = 20  // AKEYCODE_DPAD_DOWN                     = 20
	KeyCode_DpadLeft                  KeyCode = 21  // AKEYCODE_DPAD_LEFT                     = 21
	KeyCode_DpadRight                 KeyCode = 22  // AKEYCODE_DPAD_RIGHT                    = 22
	KeyCode_DpadCenter                KeyCode = 23  // AKEYCODE_DPAD_CENTER                   = 23
	KeyCode_VolumeUp                  KeyCode = 24  // AKEYCODE_VOLUME_UP                     = 24
	KeyCode_VolumeDown                KeyCode = 25  // AKEYCODE_VOLUME_DOWN                   = 25
	KeyCode_Power                     KeyCode = 26  // AKEYCODE_POWER                         = 26
	KeyCode_Camera                    KeyCode = 27  // AKEYCODE_CAMERA                        = 27
	KeyCode_Clear                     KeyCode = 28  // AKEYCODE_CLEAR                         = 28
	KeyCode_A                         KeyCode = 29  // AKEYCODE_A                             = 29
	KeyCode_B                         KeyCode = 30  // AKEYCODE_B                             = 30
	KeyCode_C                         KeyCode = 31  // AKEYCODE_C                             = 31
	KeyCode_D                         KeyCode = 32  // AKEYCODE_D                             = 32
	KeyCode_E                         KeyCode = 33  // AKEYCODE_E                             = 33
	KeyCode_F                         KeyCode = 34  // AKEYCODE_F                             = 34
	KeyCode_G                         KeyCode = 35  // AKEYCODE_G                             = 35
	KeyCode_H                         KeyCode = 36  // AKEYCODE_H                             = 36
	KeyCode_I                         KeyCode = 37  // AKEYCODE_I                             = 37
	KeyCode_J                         KeyCode = 38  // AKEYCODE_J                             = 38
	KeyCode_K                         KeyCode = 39  // AKEYCODE_K                             = 39
	KeyCode_L                         KeyCode = 40  // AKEYCODE_L                             = 40
	KeyCode_M                         KeyCode = 41  // AKEYCODE_M                             = 41
	KeyCode_N                         KeyCode = 42  // AKEYCODE_N                             = 42
	KeyCode_O                         KeyCode = 43  // AKEYCODE_O                             = 43
	KeyCode_P                         KeyCode = 44  // AKEYCODE_P                             = 44
	KeyCode_Q                         KeyCode = 45  // AKEYCODE_Q                             = 45
	KeyCode_R                         KeyCode = 46  // AKEYCODE_R                             = 46
	KeyCode_S                         KeyCode = 47  // AKEYCODE_S                             = 47
	KeyCode_T                         KeyCode = 48  // AKEYCODE_T                             = 48
	KeyCode_U                         KeyCode = 49  // AKEYCODE_U                             = 49
	KeyCode_V                         KeyCode = 50  // AKEYCODE_V                             = 50
	KeyCode_W                         KeyCode = 51  // AKEYCODE_W                             = 51
	KeyCode_X                         KeyCode = 52  // AKEYCODE_X                             = 52
	KeyCode_Y                         KeyCode = 53  // AKEYCODE_Y                             = 53
	KeyCode_Z                         KeyCode = 54  // AKEYCODE_Z                             = 54
	KeyCode_Comma                     KeyCode = 55  // AKEYCODE_COMMA                         = 55
	KeyCode_Period                    KeyCode = 56  // AKEYCODE_PERIOD                        = 56
	KeyCode_AltLeft                   KeyCode = 57  // AKEYCODE_ALT_LEFT                      = 57
	KeyCode_AltRight                  KeyCode = 58  // AKEYCODE_ALT_RIGHT                     = 58
	KeyCode_ShiftLeft                 KeyCode = 59  // AKEYCODE_SHIFT_LEFT                    = 59
	KeyCode_ShiftRight                KeyCode = 60  // AKEYCODE_SHIFT_RIGHT                   = 60
	KeyCode_Tab                       KeyCode = 61  // AKEYCODE_TAB                           = 61
	KeyCode_Space                     KeyCode = 62  // AKEYCODE_SPACE                         = 62
	KeyCode_Sym                       KeyCode = 63  // AKEYCODE_SYM                           = 63
	KeyCode_Explorer                  KeyCode = 64  // AKEYCODE_EXPLORER                      = 64
	KeyCode_Envelope                  KeyCode = 65  // AKEYCODE_ENVELOPE                      = 65
	KeyCode_Enter                     KeyCode = 66  // AKEYCODE_ENTER                         = 66
	KeyCode_Del                       KeyCode = 67  // AKEYCODE_DEL                           = 67
	KeyCode_Grave                     KeyCode = 68  // AKEYCODE_GRAVE                         = 68
	KeyCode_Minus                     KeyCode = 69  // AKEYCODE_MINUS                         = 69
	KeyCode_Equals                    KeyCode = 70  // AKEYCODE_EQUALS                        = 70
	KeyCode_LeftBracket               KeyCode = 71  // AKEYCODE_LEFT_BRACKET                  = 71
	KeyCode_RightBracket              KeyCode = 72  // AKEYCODE_RIGHT_BRACKET                 = 72
	KeyCode_Backslash                 KeyCode = 73  // AKEYCODE_BACKSLASH                     = 73
	KeyCode_Semicolon                 KeyCode = 74  // AKEYCODE_SEMICOLON                     = 74
	KeyCode_Apostrophe                KeyCode = 75  // AKEYCODE_APOSTROPHE                    = 75
	KeyCode_Slash                     KeyCode = 76  // AKEYCODE_SLASH                         = 76
	KeyCode_At                        KeyCode = 77  // AKEYCODE_AT                            = 77
	KeyCode_Num                       KeyCode = 78  // AKEYCODE_NUM                           = 78
	KeyCode_Headsethook               KeyCode = 79  // AKEYCODE_HEADSETHOOK                   = 79
	KeyCode_Focus                     KeyCode = 80  // AKEYCODE_FOCUS                         = 80
	KeyCode_Plus                      KeyCode = 81  // AKEYCODE_PLUS                          = 81
	KeyCode_Menu                      KeyCode = 82  // AKEYCODE_MENU                          = 82
	KeyCode_Notification              KeyCode = 83  // AKEYCODE_NOTIFICATION                  = 83
	KeyCode_Search                    KeyCode = 84  // AKEYCODE_SEARCH                        = 84
	KeyCode_MediaPlayPause            KeyCode = 85  // AKEYCODE_MEDIA_PLAY_PAUSE              = 85
	KeyCode_MediaStop                 KeyCode = 86  // AKEYCODE_MEDIA_STOP                    = 86
	KeyCode_MediaNext                 KeyCode = 87  // AKEYCODE_MEDIA_NEXT                    = 87
	KeyCode_MediaPrevious             KeyCode = 88  // AKEYCODE_MEDIA_PREVIOUS                = 88
	KeyCode_MediaRewind               KeyCode = 89  // AKEYCODE_MEDIA_REWIND                  = 89
	KeyCode_MediaFastForward          KeyCode = 90  // AKEYCODE_MEDIA_FAST_FORWARD            = 90
	KeyCode_Mute                      KeyCode = 91  // AKEYCODE_MUTE                          = 91
	KeyCode_PageUp                    KeyCode = 92  // AKEYCODE_PAGE_UP                       = 92
	KeyCode_PageDown                  KeyCode = 93  // AKEYCODE_PAGE_DOWN                     = 93
	KeyCode_Pictsymbols               KeyCode = 94  // AKEYCODE_PICTSYMBOLS                   = 94
	KeyCode_SwitchCharset             KeyCode = 95  // AKEYCODE_SWITCH_CHARSET                = 95
	KeyCode_ButtonA                   KeyCode = 96  // AKEYCODE_BUTTON_A                      = 96
	KeyCode_ButtonB                   KeyCode = 97  // AKEYCODE_BUTTON_B                      = 97
	KeyCode_ButtonC                   KeyCode = 98  // AKEYCODE_BUTTON_C                      = 98
	KeyCode_ButtonX                   KeyCode = 99  // AKEYCODE_BUTTON_X                      = 99
	KeyCode_ButtonY                   KeyCode = 100 // AKEYCODE_BUTTON_Y                      = 100
	KeyCode_ButtonZ                   KeyCode = 101 // AKEYCODE_BUTTON_Z                      = 101
	KeyCode_ButtonL1                  KeyCode = 102 // AKEYCODE_BUTTON_L1                     = 102
	KeyCode_ButtonR1                  KeyCode = 103 // AKEYCODE_BUTTON_R1                     = 103
	KeyCode_ButtonL2                  KeyCode = 104 // AKEYCODE_BUTTON_L2                     = 104
	KeyCode_ButtonR2                  KeyCode = 105 // AKEYCODE_BUTTON_R2                     = 105
	KeyCode_ButtonThumbl              KeyCode = 106 // AKEYCODE_BUTTON_THUMBL                 = 106
	KeyCode_ButtonThumbr              KeyCode = 107 // AKEYCODE_BUTTON_THUMBR                 = 107
	KeyCode_ButtonStart               KeyCode = 108 // AKEYCODE_BUTTON_START                  = 108
	KeyCode_ButtonSelect              KeyCode = 109 // AKEYCODE_BUTTON_SELECT                 = 109
	KeyCode_ButtonMode                KeyCode = 110 // AKEYCODE_BUTTON_MODE                   = 110
	KeyCode_Escape                    KeyCode = 111 // AKEYCODE_ESCAPE                        = 111
	KeyCode_ForwardDel                KeyCode = 112 // AKEYCODE_FORWARD_DEL                   = 112
	KeyCode_CtrlLeft                  KeyCode = 113 // AKEYCODE_CTRL_LEFT                     = 113
	KeyCode_CtrlRight                 KeyCode = 114 // AKEYCODE_CTRL_RIGHT                    = 114
	KeyCode_CapsLock                  KeyCode = 115 // AKEYCODE_CAPS_LOCK                     = 115
	KeyCode_ScrollLock                KeyCode = 116 // AKEYCODE_SCROLL_LOCK                   = 116
	KeyCode_MetaLeft                  KeyCode = 117 // AKEYCODE_META_LEFT                     = 117
	KeyCode_MetaRight                 KeyCode = 118 // AKEYCODE_META_RIGHT                    = 118
	KeyCode_Function                  KeyCode = 119 // AKEYCODE_FUNCTION                      = 119
	KeyCode_Sysrq                     KeyCode = 120 // AKEYCODE_SYSRQ                         = 120
	KeyCode_Break                     KeyCode = 121 // AKEYCODE_BREAK                         = 121
	KeyCode_MoveHome                  KeyCode = 122 // AKEYCODE_MOVE_HOME                     = 122
	KeyCode_MoveEnd                   KeyCode = 123 // AKEYCODE_MOVE_END                      = 123
	KeyCode_Insert                    KeyCode = 124 // AKEYCODE_INSERT                        = 124
	KeyCode_Forward                   KeyCode = 125 // AKEYCODE_FORWARD                       = 125
	KeyCode_MediaPlay                 KeyCode = 126 // AKEYCODE_MEDIA_PLAY                    = 126
	KeyCode_MediaPause                KeyCode = 127 // AKEYCODE_MEDIA_PAUSE                   = 127
	KeyCode_MediaClose                KeyCode = 128 // AKEYCODE_MEDIA_CLOSE                   = 128
	KeyCode_MediaEject                KeyCode = 129 // AKEYCODE_MEDIA_EJECT                   = 129
	KeyCode_MediaRecord               KeyCode = 130 // AKEYCODE_MEDIA_RECORD                  = 130
	KeyCode_F1                        KeyCode = 131 // AKEYCODE_F1                            = 131
	KeyCode_F2                        KeyCode = 132 // AKEYCODE_F2                            = 132
	KeyCode_F3                        KeyCode = 133 // AKEYCODE_F3                            = 133
	KeyCode_F4                        KeyCode = 134 // AKEYCODE_F4                            = 134
	KeyCode_F5                        KeyCode = 135 // AKEYCODE_F5                            = 135
	KeyCode_F6                        KeyCode = 136 // AKEYCODE_F6                            = 136
	KeyCode_F7                        KeyCode = 137 // AKEYCODE_F7                            = 137
	KeyCode_F8                        KeyCode = 138 // AKEYCODE_F8                            = 138
	KeyCode_F9                        KeyCode = 139 // AKEYCODE_F9                            = 139
	KeyCode_F10                       KeyCode = 140 // AKEYCODE_F10                           = 140
	KeyCode_F11                       KeyCode = 141 // AKEYCODE_F11                           = 141
	KeyCode_F12                       KeyCode = 142 // AKEYCODE_F12                           = 142
	KeyCode_NumLock                   KeyCode = 143 // AKEYCODE_NUM_LOCK                      = 143
	KeyCode_Numpad0                   KeyCode = 144 // AKEYCODE_NUMPAD_0                      = 144
	KeyCode_Numpad1                   KeyCode = 145 // AKEYCODE_NUMPAD_1                      = 145
	KeyCode_Numpad2                   KeyCode = 146 // AKEYCODE_NUMPAD_2                      = 146
	KeyCode_Numpad3                   KeyCode = 147 // AKEYCODE_NUMPAD_3                      = 147
	KeyCode_Numpad4                   KeyCode = 148 // AKEYCODE_NUMPAD_4                      = 148
	KeyCode_Numpad5                   KeyCode = 149 // AKEYCODE_NUMPAD_5                      = 149
	KeyCode_Numpad6                   KeyCode = 150 // AKEYCODE_NUMPAD_6                      = 150
	KeyCode_Numpad7                   KeyCode = 151 // AKEYCODE_NUMPAD_7                      = 151
	KeyCode_Numpad8                   KeyCode = 152 // AKEYCODE_NUMPAD_8                      = 152
	KeyCode_Numpad9                   KeyCode = 153 // AKEYCODE_NUMPAD_9                      = 153
	KeyCode_NumpadDivide              KeyCode = 154 // AKEYCODE_NUMPAD_DIVIDE                 = 154
	KeyCode_NumpadMultiply            KeyCode = 155 // AKEYCODE_NUMPAD_MULTIPLY               = 155
	KeyCode_NumpadSubtract            KeyCode = 156 // AKEYCODE_NUMPAD_SUBTRACT               = 156
	KeyCode_NumpadAdd                 KeyCode = 157 // AKEYCODE_NUMPAD_ADD                    = 157
	KeyCode_NumpadDot                 KeyCode = 158 // AKEYCODE_NUMPAD_DOT                    = 158
	KeyCode_NumpadComma               KeyCode = 159 // AKEYCODE_NUMPAD_COMMA                  = 159
	KeyCode_NumpadEnter               KeyCode = 160 // AKEYCODE_NUMPAD_ENTER                  = 160
	KeyCode_NumpadEquals              KeyCode = 161 // AKEYCODE_NUMPAD_EQUALS                 = 161
	KeyCode_NumpadLeftParen           KeyCode = 162 // AKEYCODE_NUMPAD_LEFT_PAREN             = 162
	KeyCode_NumpadRightParen          KeyCode = 163 // AKEYCODE_NUMPAD_RIGHT_PAREN            = 163
	KeyCode_VolumeMute                KeyCode = 164 // AKEYCODE_VOLUME_MUTE                   = 164
	KeyCode_Info                      KeyCode = 165 // AKEYCODE_INFO                          = 165
	KeyCode_ChannelUp                 KeyCode = 166 // AKEYCODE_CHANNEL_UP                    = 166
	KeyCode_ChannelDown               KeyCode = 167 // AKEYCODE_CHANNEL_DOWN                  = 167
	KeyCode_ZoomIn                    KeyCode = 168 // AKEYCODE_ZOOM_IN                       = 168
	KeyCode_ZoomOut                   KeyCode = 169 // AKEYCODE_ZOOM_OUT                      = 169
	KeyCode_Tv                        KeyCode = 170 // AKEYCODE_TV                            = 170
	KeyCode_Window                    KeyCode = 171 // AKEYCODE_WINDOW                        = 171
	KeyCode_Guide                     KeyCode = 172 // AKEYCODE_GUIDE                         = 172
	KeyCode_Dvr                       KeyCode = 173 // AKEYCODE_DVR                           = 173
	KeyCode_Bookmark                  KeyCode = 174 // AKEYCODE_BOOKMARK                      = 174
	KeyCode_Captions                  KeyCode = 175 // AKEYCODE_CAPTIONS                      = 175
	KeyCode_Settings                  KeyCode = 176 // AKEYCODE_SETTINGS                      = 176
	KeyCode_TvPower                   KeyCode = 177 // AKEYCODE_TV_POWER                      = 177
	KeyCode_TvInput                   KeyCode = 178 // AKEYCODE_TV_INPUT                      = 178
	KeyCode_StbPower                  KeyCode = 179 // AKEYCODE_STB_POWER                     = 179
	KeyCode_StbInput                  KeyCode = 180 // AKEYCODE_STB_INPUT                     = 180
	KeyCode_AvrPower                  KeyCode = 181 // AKEYCODE_AVR_POWER                     = 181
	KeyCode_AvrInput                  KeyCode = 182 // AKEYCODE_AVR_INPUT                     = 182
	KeyCode_ProgRed                   KeyCode = 183 // AKEYCODE_PROG_RED                      = 183
	KeyCode_ProgGreen                 KeyCode = 184 // AKEYCODE_PROG_GREEN                    = 184
	KeyCode_ProgYellow                KeyCode = 185 // AKEYCODE_PROG_YELLOW                   = 185
	KeyCode_ProgBlue                  KeyCode = 186 // AKEYCODE_PROG_BLUE                     = 186
	KeyCode_AppSwitch                 KeyCode = 187 // AKEYCODE_APP_SWITCH                    = 187
	KeyCode_Button1                   KeyCode = 188 // AKEYCODE_BUTTON_1                      = 188
	KeyCode_Button2                   KeyCode = 189 // AKEYCODE_BUTTON_2                      = 189
	KeyCode_Button3                   KeyCode = 190 // AKEYCODE_BUTTON_3                      = 190
	KeyCode_Button4                   KeyCode = 191 // AKEYCODE_BUTTON_4                      = 191
	KeyCode_Button5                   KeyCode = 192 // AKEYCODE_BUTTON_5                      = 192
	KeyCode_Button6                   KeyCode = 193 // AKEYCODE_BUTTON_6                      = 193
	KeyCode_Button7                   KeyCode = 194 // AKEYCODE_BUTTON_7                      = 194
	KeyCode_Button8                   KeyCode = 195 // AKEYCODE_BUTTON_8                      = 195
	KeyCode_Button9                   KeyCode = 196 // AKEYCODE_BUTTON_9                      = 196
	KeyCode_Button10                  KeyCode = 197 // AKEYCODE_BUTTON_10                     = 197
	KeyCode_Button11                  KeyCode = 198 // AKEYCODE_BUTTON_11                     = 198
	KeyCode_Button12                  KeyCode = 199 // AKEYCODE_BUTTON_12                     = 199
	KeyCode_Button13                  KeyCode = 200 // AKEYCODE_BUTTON_13                     = 200
	KeyCode_Button14                  KeyCode = 201 // AKEYCODE_BUTTON_14                     = 201
	KeyCode_Button15                  KeyCode = 202 // AKEYCODE_BUTTON_15                     = 202
	KeyCode_Button16                  KeyCode = 203 // AKEYCODE_BUTTON_16                     = 203
	KeyCode_LanguageSwitch            KeyCode = 204 // AKEYCODE_LANGUAGE_SWITCH               = 204
	KeyCode_MannerMode                KeyCode = 205 // AKEYCODE_MANNER_MODE                   = 205
	KeyCode_3dMode                    KeyCode = 206 // AKEYCODE_3D_MODE                       = 206
	KeyCode_Contacts                  KeyCode = 207 // AKEYCODE_CONTACTS                      = 207
	KeyCode_Calendar                  KeyCode = 208 // AKEYCODE_CALENDAR                      = 208
	KeyCode_Music                     KeyCode = 209 // AKEYCODE_MUSIC                         = 209
	KeyCode_Calculator                KeyCode = 210 // AKEYCODE_CALCULATOR                    = 210
	KeyCode_ZenkakuHankaku            KeyCode = 211 // AKEYCODE_ZENKAKU_HANKAKU               = 211
	KeyCode_Eisu                      KeyCode = 212 // AKEYCODE_EISU                          = 212
	KeyCode_Muhenkan                  KeyCode = 213 // AKEYCODE_MUHENKAN                      = 213
	KeyCode_Henkan                    KeyCode = 214 // AKEYCODE_HENKAN                        = 214
	KeyCode_KatakanaHiragana          KeyCode = 215 // AKEYCODE_KATAKANA_HIRAGANA             = 215
	KeyCode_Yen                       KeyCode = 216 // AKEYCODE_YEN                           = 216
	KeyCode_Ro                        KeyCode = 217 // AKEYCODE_RO                            = 217
	KeyCode_Kana                      KeyCode = 218 // AKEYCODE_KANA                          = 218
	KeyCode_Assist                    KeyCode = 219 // AKEYCODE_ASSIST                        = 219
	KeyCode_BrightnessDown            KeyCode = 220 // AKEYCODE_BRIGHTNESS_DOWN               = 220
	KeyCode_BrightnessUp              KeyCode = 221 // AKEYCODE_BRIGHTNESS_UP                 = 221
	KeyCode_MediaAudioTrack           KeyCode = 222 // AKEYCODE_MEDIA_AUDIO_TRACK             = 222
	KeyCode_Sleep                     KeyCode = 223 // AKEYCODE_SLEEP                         = 223
	KeyCode_Wakeup                    KeyCode = 224 // AKEYCODE_WAKEUP                        = 224
	KeyCode_Pairing                   KeyCode = 225 // AKEYCODE_PAIRING                       = 225
	KeyCode_MediaTopMenu              KeyCode = 226 // AKEYCODE_MEDIA_TOP_MENU                = 226
	KeyCode_11                        KeyCode = 227 // AKEYCODE_11                            = 227
	KeyCode_12                        KeyCode = 228 // AKEYCODE_12                            = 228
	KeyCode_LastChannel               KeyCode = 229 // AKEYCODE_LAST_CHANNEL                  = 229
	KeyCode_TvDataService             KeyCode = 230 // AKEYCODE_TV_DATA_SERVICE               = 230
	KeyCode_VoiceAssist               KeyCode = 231 // AKEYCODE_VOICE_ASSIST                  = 231
	KeyCode_TvRadioService            KeyCode = 232 // AKEYCODE_TV_RADIO_SERVICE              = 232
	KeyCode_TvTeletext                KeyCode = 233 // AKEYCODE_TV_TELETEXT                   = 233
	KeyCode_TvNumberEntry             KeyCode = 234 // AKEYCODE_TV_NUMBER_ENTRY               = 234
	KeyCode_TvTerrestrialAnalog       KeyCode = 235 // AKEYCODE_TV_TERRESTRIAL_ANALOG         = 235
	KeyCode_TvTerrestrialDigital      KeyCode = 236 // AKEYCODE_TV_TERRESTRIAL_DIGITAL        = 236
	KeyCode_TvSatellite               KeyCode = 237 // AKEYCODE_TV_SATELLITE                  = 237
	KeyCode_TvSatelliteBs             KeyCode = 238 // AKEYCODE_TV_SATELLITE_BS               = 238
	KeyCode_TvSatelliteCs             KeyCode = 239 // AKEYCODE_TV_SATELLITE_CS               = 239
	KeyCode_TvSatelliteService        KeyCode = 240 // AKEYCODE_TV_SATELLITE_SERVICE          = 240
	KeyCode_TvNetwork                 KeyCode = 241 // AKEYCODE_TV_NETWORK                    = 241
	KeyCode_TvAntennaCable            KeyCode = 242 // AKEYCODE_TV_ANTENNA_CABLE              = 242
	KeyCode_TvInputHdmi1              KeyCode = 243 // AKEYCODE_TV_INPUT_HDMI_1               = 243
	KeyCode_TvInputHdmi2              KeyCode = 244 // AKEYCODE_TV_INPUT_HDMI_2               = 244
	KeyCode_TvInputHdmi3              KeyCode = 245 // AKEYCODE_TV_INPUT_HDMI_3               = 245
	KeyCode_TvInputHdmi4              KeyCode = 246 // AKEYCODE_TV_INPUT_HDMI_4               = 246
	KeyCode_TvInputComposite1         KeyCode = 247 // AKEYCODE_TV_INPUT_COMPOSITE_1          = 247
	KeyCode_TvInputComposite2         KeyCode = 248 // AKEYCODE_TV_INPUT_COMPOSITE_2          = 248
	KeyCode_TvInputComponent1         KeyCode = 249 // AKEYCODE_TV_INPUT_COMPONENT_1          = 249
	KeyCode_TvInputComponent2         KeyCode = 250 // AKEYCODE_TV_INPUT_COMPONENT_2          = 250
	KeyCode_TvInputVga1               KeyCode = 251 // AKEYCODE_TV_INPUT_VGA_1                = 251
	KeyCode_TvAudioDescription        KeyCode = 252 // AKEYCODE_TV_AUDIO_DESCRIPTION          = 252
	KeyCode_TvAudioDescriptionMixUp   KeyCode = 253 // AKEYCODE_TV_AUDIO_DESCRIPTION_MIX_UP   = 253
	KeyCode_TvAudioDescriptionMixDown KeyCode = 254 // AKEYCODE_TV_AUDIO_DESCRIPTION_MIX_DOWN = 254
	KeyCode_TvZoomMode                KeyCode = 255 // AKEYCODE_TV_ZOOM_MODE                  = 255
	KeyCode_TvContentsMenu            KeyCode = 256 // AKEYCODE_TV_CONTENTS_MENU              = 256
	KeyCode_TvMediaContextMenu        KeyCode = 257 // AKEYCODE_TV_MEDIA_CONTEXT_MENU         = 257
	KeyCode_TvTimerProgramming        KeyCode = 258 // AKEYCODE_TV_TIMER_PROGRAMMING          = 258
	KeyCode_Help                      KeyCode = 259 // AKEYCODE_HELP                          = 259
	KeyCode_NavigatePrevious          KeyCode = 260 // AKEYCODE_NAVIGATE_PREVIOUS             = 260
	KeyCode_NavigateNext              KeyCode = 261 // AKEYCODE_NAVIGATE_NEXT                 = 261
	KeyCode_NavigateIn                KeyCode = 262 // AKEYCODE_NAVIGATE_IN                   = 262
	KeyCode_NavigateOut               KeyCode = 263 // AKEYCODE_NAVIGATE_OUT                  = 263
	KeyCode_StemPrimary               KeyCode = 264 // AKEYCODE_STEM_PRIMARY                  = 264
	KeyCode_Stem1                     KeyCode = 265 // AKEYCODE_STEM_1                        = 265
	KeyCode_Stem2                     KeyCode = 266 // AKEYCODE_STEM_2                        = 266
	KeyCode_Stem3                     KeyCode = 267 // AKEYCODE_STEM_3                        = 267
	KeyCode_DpadUpLeft                KeyCode = 268 // AKEYCODE_DPAD_UP_LEFT                  = 268
	KeyCode_DpadDownLeft              KeyCode = 269 // AKEYCODE_DPAD_DOWN_LEFT                = 269
	KeyCode_DpadUpRight               KeyCode = 270 // AKEYCODE_DPAD_UP_RIGHT                 = 270
	KeyCode_DpadDownRight             KeyCode = 271 // AKEYCODE_DPAD_DOWN_RIGHT               = 271
	KeyCode_MediaSkipForward          KeyCode = 272 // AKEYCODE_MEDIA_SKIP_FORWARD            = 272
	KeyCode_MediaSkipBackward         KeyCode = 273 // AKEYCODE_MEDIA_SKIP_BACKWARD           = 273
	KeyCode_MediaStepForward          KeyCode = 274 // AKEYCODE_MEDIA_STEP_FORWARD            = 274
	KeyCode_MediaStepBackward         KeyCode = 275 // AKEYCODE_MEDIA_STEP_BACKWARD           = 275
	KeyCode_SoftSleep                 KeyCode = 276 // AKEYCODE_SOFT_SLEEP                    = 276
	KeyCode_Cut                       KeyCode = 277 // AKEYCODE_CUT                           = 277
	KeyCode_Copy                      KeyCode = 278 // AKEYCODE_COPY                          = 278
	KeyCode_Paste                     KeyCode = 279 // AKEYCODE_PASTE                         = 279
	KeyCode_SystemNavigationUp        KeyCode = 280 // AKEYCODE_SYSTEM_NAVIGATION_UP          = 280
	KeyCode_SystemNavigationDown      KeyCode = 281 // AKEYCODE_SYSTEM_NAVIGATION_DOWN        = 281
	KeyCode_SystemNavigationLeft      KeyCode = 282 // AKEYCODE_SYSTEM_NAVIGATION_LEFT        = 282
	KeyCode_SystemNavigationRight     KeyCode = 283 // AKEYCODE_SYSTEM_NAVIGATION_RIGHT       = 283
	KeyCode_AllApps                   KeyCode = 284 // AKEYCODE_ALL_APPS                      = 284
	KeyCode_Refresh                   KeyCode = 285 // AKEYCODE_REFRESH                       = 285
	KeyCode_ThumbsUp                  KeyCode = 286 // AKEYCODE_THUMBS_UP                     = 286
	KeyCode_ThumbsDown                KeyCode = 287 // AKEYCODE_THUMBS_DOWN                   = 287
	KeyCode_ProfileSwitch             KeyCode = 288 // AKEYCODE_PROFILE_SWITCH                = 288
)
